db:
  type: "mysql"
  config:
    host: "114.55.128.130"
    port: "33061"
    db:  "gin_blog"
    user: "root"
    password: "n208966737"
    maxCon: 500
    maxIdle: 20

redis:
  host: "114.55.128.130"
  port: "63791"
  db: 0
  poolSize: 50

app:
  port: "8080"
  host: "0.0.0.0"

jwt:
  secret: "xlszxjm"